variable "rg_central_name" {}
variable "rg_central_location" {}

variable "gateway_vnet_name" {}
variable "gateway_vnet_cidr" {}
variable "agw_subnet_name" {}
variable "agw_subnet_cidr" {}
variable "app_vnet_name" {}
variable "app_vnet_cidr" {}
variable "endpoint_subnet_name" {}
variable "endpoint_subnet_cidr" {}
variable "integration_subnet_name" {}
variable "integration_subnet_cidr" {}
variable "ai_vm_subnet_name" {}
variable "ai_vm_subnet_cidr" {}
variable "bastion_subnet_name" {}
variable "bastion_subnet_cidr" {}
variable "nat_gateway_name" {}
variable "nat_public_ip_name" {}
variable "agw_name" {}
variable "agw_public_ip_name" {}
variable "waf_policy_name" {}
variable "app_service_plan_name" {}
variable "frontend_app_name" {}
variable "backend_app_name" {}
variable "app_service_dns_name" {}
variable "cosmos_dns_name" {}
variable "cosmos_account_name" {}
variable "cosmos_mongo_db_name" {}
variable "storage_account_name" {}
variable "frontend_pe_name" {}
variable "backend_pe_name" {}
variable "cosmos_pe_name" {}
variable "ai_vm_name" {}
variable "ai_vm_nic_name" {}
variable "ai_vm_nsg_name" {}
variable "ai_vm_admin_username" {}
variable "ai_vm_admin_password" {}
variable "ai_vm_private_ip_address" {}
variable "bastion_name" {}
variable "bastion_public_ip_name" {}
variable "tags" {}

variable "next_public_api_url" {}
variable "ollama_url" {}
variable "mongodb_database" {}
variable "scm_do_build_during_deployment" {}
